name: Build MyffmpegMake

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      squid-proxy:
        image: ubuntu/squid:latest
        ports:
          - 3128:3128
 
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: KeepLive
      run: touch /tmp/keepalive
      
    - name: SetEnv
      run:  |
             eval ${{ vars.SETENV1 }}
             eval ${{ vars.SETENV2 }}
             eval ${{ vars.SETENV3 }}
             eval ${{ vars.SETENV4 }} 
             
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y nasm 
        sudo apt-get install -y \
            autoconf \
            automake \
            build-essential \
            cmake \
            git \
            libass-dev \
            libfreetype6-dev \
            libsdl2-dev \
            libtool \
            libva-dev \
            libvdpau-dev \
            libvorbis-dev \
            libxcb1-dev \
            libxcb-shm0-dev \
            libxcb-xfixes0-dev \
            pkg-config \
            texinfo \
            wget \
            yasm \
            zlib1g-dev \
            libx264-dev \
            libx265-dev \
            libvpx-dev \
            libfdk-aac-dev \
            libmp3lame-dev \
            libopus-dev

    - name: Download FFmpeg source
      run: |
        wget https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2
        tar -xjf ffmpeg-snapshot.tar.bz2
        cd ffmpeg
        
    - name: Configure FFmpeg
      run: |
          sudo  ./configure \
            --prefix=/usr/local \
            --enable-gpl \
            --enable-libass \
            --enable-libfdk-aac \
            --enable-libfreetype \
            --enable-libmp3lame \
            --enable-libopus \
            --enable-libvorbis \
            --enable-libvpx \
            --enable-libx264 \
            --enable-libx265 \
            --enable-nonfree
            
      working-directory: ffmpeg
    - name: Compile FFmpeg
      run: |
        make -j$(nproc)

      working-directory: ffmpeg
    - name: Install FFmpeg
      run: |
        sudo make install

      working-directory: ffmpeg
    - name: Verify FFmpeg installation
      run: |
          ffmpeg -version

    - name: Upload FFmpeg as artifact (optional)
      uses: actions/upload-artifact@v3
      with:
          name: ffmpeg-binaries
          path: /usr/local/bin/ffmpeg
