name: Build FFmpeg

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y yasm nasm autoconf automake build-essential cmake git libtool pkg-config zlib1g-dev

    - name: Download FFmpeg source
      run: |
        wget https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2
        tar -xjf ffmpeg-snapshot.tar.bz2
        cd ffmpeg*

    - name: Configure FFmpeg
      run: |
        sudo ./configure --enable-gpl --enable-libx264 --enable-libx265 --enable-libvpx --enable-libfdk-aac --enable-nonfree

      working-directory: ffmpeg*

    - name: Compile FFmpeg
      run: |
        make -j$(nproc)

      working-directory: ffmpeg*

    - name: Install FFmpeg
      run: |
        sudo make install

      working-directory: ffmpeg*

    - name: Verify installation
      run: |
        ffmpeg -version
