name: Build FFmpeg

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y nasm 
        sudo apt-get install -y \
            autoconf \
            automake \
            build-essential \
            cmake \
            git \
            libass-dev \
            libfreetype6-dev \
            libsdl2-dev \
            libtool \
            libva-dev \
            libvdpau-dev \
            libvorbis-dev \
            libxcb1-dev \
            libxcb-shm0-dev \
            libxcb-xfixes0-dev \
            pkg-config \
            texinfo \
            wget \
            yasm \
            zlib1g-dev \
            libx264-dev \
            libx265-dev \
            libvpx-dev \
            libfdk-aac-dev \
            libmp3lame-dev \
            libopus-dev

    - name: Download FFmpeg source
      run: |
        wget https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2
        tar -xjf ffmpeg-snapshot.tar.bz2
        cd ffmpeg

    - name: Configure FFmpeg
      run: |
        sudo ./configure --enable-gpl --enable-libx264 --enable-libx265 --enable-libvpx --enable-libfdk-aac --enable-nonfree

      working-directory: ffmpeg

    - name: Compile FFmpeg
      run: |
        make -j$(nproc)

      working-directory: ffmpeg

    - name: Install FFmpeg
      run: |
        sudo make install

      working-directory: ffmpeg

    - name: Verify installation
      run: |
        ffmpeg -version
